- name: Install Git
  community.general.homebrew:
    name: git
    state: present
  tags:
    - git
- name: Link .gitconfig
  ansible.builtin.file:
    src: "{{ config.src }}"
    dest: "{{ config.dest }}"
    state: link
    force: true
  tags:
    - git
    - dotfiles
