- name: Fetch NVM installation script
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh
    return_content: true
  register: nvm_install
  tags:
    - node
- name: Install NVM
  ansible.builtin.shell: "{{ nvm_install.content }}"
  args:
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.nvm/nvm.sh"
  tags:
    - node
- name: Install Node
  args:
    executable: /bin/bash
  ansible.builtin.shell: source "{{ lookup('ansible.builtin.env', 'HOME') }}/.nvm/nvm.sh" && nvm install --lts
  tags:
    - node
