- name: Install Vim
  community.general.homebrew:
    name: vim
    state: present
  tags:
    - vim
- name: Create .vim directories
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.vim/autoload"
    state: directory
  tags:
    - vim
- name: Install vim-plug
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.vim/autoload/plug.vim"
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.vim/autoload/plug.vim"
  tags:
    - vim
- name: Link .vimrc
  ansible.builtin.file:
    src: "{{ config.src }}"
    dest: "{{ config.dest }}"
    state: link
    force: true
  tags:
    - vim
    - dotfiles
