- name: Install Vim
  community.general.homebrew:
    name: vim
    state: present
  tags:
    - vim
- name: Create .vim directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory
  tags:
    - vim
- name: Install vim-plug
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    creates: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
  tags:
    - vim
- name: Link .vimrc
  ansible.builtin.file:
    src: "{{ playbook_dir }}/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link
    force: true
  tags:
    - vim
    - link
